### ISSUE TITLE
[RFC 0070] New fields in buildpack.toml

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/docs#342] opened 2021-03-25 20:57 UTC
Apologies if this is duplicated elsewhere, I couldn't find it.

Document new fields described in [RFC 0070](https://github.com/buildpacks/rfcs/pull/127)

**Comment by samj1912** [comment] 2021-07-29 11:37
Duplicate of https://github.com/buildpacks/docs/issues/288

Closing this one for now.

**Closed by samj1912** 2021-07-29 11:37 UTC
Labels: team/buildpack-authors-tooling, team/implementations, type/enhancement
