### ISSUE TITLE
ERROR: failed to export: determining entrypoint: tried to set web to default but it doesn't exist

### ISSUE THREAD

**Issue by Sunny-001** [buildpacks/docs#534] opened 2022-11-22 10:44 UTC
**On Page:** [Mounting Volumes](https://buildpacks.io/docs/app-developer-guide/mounting-volumes/)
when i build a vue project, the tekton buildpacks occurred an error as follows:
```
===> ANALYZING
Previous image with name "[registry.cn-hangzhou.aliyuncs.com/cached/ruoyi-ui:3.0.0](http://registry.cn-hangzhou.aliyuncs.com/cached/ruoyi-ui:3.0.0)" not found
===> DETECTING
5 of 12 buildpacks participating
paketo-buildpacks/ca-certificates 3.4.0
paketo-buildpacks/node-engine     0.19.0
paketo-buildpacks/npm-install     0.10.8
paketo-buildpacks/node-module-bom 0.4.3
paketo-buildpacks/node-run-script 0.5.1
===> RESTORING
Restoring data for SBOM from cache
===> BUILDING
Paketo Buildpack for CA Certificates 3.4.0
  https://github.com/paketo-buildpacks/ca-certificates
  Launch Helper: Contributing to layer
    Creating /layers/paketo-buildpacks_ca-certificates/helper/exec.d/ca-certificates-helper
Paketo Buildpack for Node Engine 0.19.0
  Resolving Node Engine version
    Candidate version sources (in priority order):
      BP_NODE_VERSION -> "16.18.0"
      package.json    -> ">=8.9"
      <unknown>       -> ""

    Selected Node Engine version (using BP_NODE_VERSION): 16.18.0

  Executing build process
    Installing Node Engine 16.18.0
      Completed in 2.794s

  Generating SBOM for /layers/paketo-buildpacks_node-engine/node
      Completed in 68ms

  Configuring build environment
    NODE_ENV     -> "production"
    NODE_HOME    -> "/layers/paketo-buildpacks_node-engine/node"
    NODE_VERBOSE -> "false"

  Configuring launch environment
    NODE_ENV     -> "production"
    NODE_HOME    -> "/layers/paketo-buildpacks_node-engine/node"
    NODE_VERBOSE -> "false"

    Writing exec.d/0-optimize-memory
      Calculates available memory based on container limits at launch time.
      Made available in the MEMORY_AVAILABLE environment variable.

Paketo Buildpack for NPM Install 0.10.8
  Resolving installation process
    Process inputs:
      node_modules      -> "Not found"
      npm-cache         -> "Not found"
      package-lock.json -> "Not found"

    Selected NPM build process: 'npm install'

  Executing build environment install process
    Running 'npm install --unsafe-perm --cache /layers/paketo-buildpacks_npm-install/npm-cache'
      Completed in 4m18.519s

  Configuring build environment
    NODE_ENV -> "development"
    PATH     -> "$PATH:/layers/paketo-buildpacks_npm-install/build-modules/node_modules/.bin"

  Generating SBOM for /layers/paketo-buildpacks_npm-install/build-modules
      Completed in 40.725s


Paketo Buildpack for Node Module Bill of Materials Generator 0.4.3
  Resolving CycloneDX Node.js Module version
    Selected CycloneDX Node.js Module version: 3.10.4

  Executing build process
    Installing CycloneDX Node.js Module 3.10.4
      Completed in 1.004s

  Configuring environment
    Appending CycloneDX Node.js Module onto PATH

  Running CycloneDX Node.js Module
    Running 'cyclonedx-bom -o bom.json'
      Completed in 2.361s

Warning: BOM table is deprecated in this buildpack api version, though it remains supported for backwards compatibility. Buildpack authors should write BOM information to <layer>.sbom.<ext>, launch.sbom.<ext>, or build.sbom.<ext>.
Warning: BOM table is deprecated in this buildpack api version, though it remains supported for backwards compatibility. Buildpack authors should write BOM information to <layer>.sbom.<ext>, launch.sbom.<ext>, or build.sbom.<ext>.
Warning: BOM table is deprecated in this buildpack api version, though it remains supported for backwards compatibility. Buildpack authors should write BOM information to <layer>.sbom.<ext>, launch.sbom.<ext>, or build.sbom.<ext>.
Paketo Buildpack for Node Run Script 0.5.1
  Executing build process
    Running 'npm run build:prod'
      
      > ruoyi@3.8.4 build:prod
      > vue-cli-service build
      
      
      -  Building for production...
       DONE  Compiled successfully in 23336ms10:29:48 AM
      
        File                               Size                Gzipped
      
        dist/static/js/11.js               6000.71 KiB         890.56 KiB
        dist/static/js/chunk-vendors.js    3784.00 KiB         654.99 KiB
        dist/static/js/app.js              3195.49 KiB         235.49 KiB
        dist/static/js/0.js                463.33 KiB          75.39 KiB
        dist/static/js/1.js                209.09 KiB          30.38 KiB
        dist/static/js/6.js                132.24 KiB          18.09 KiB
        dist/static/js/2.js                102.79 KiB          22.72 KiB
        dist/static/js/3.js                61.57 KiB           6.19 KiB
        dist/static/js/7.js                45.72 KiB           5.04 KiB
        dist/static/js/9.js                44.89 KiB           6.00 KiB
        dist/static/js/8.js                42.83 KiB           5.74 KiB
        dist/static/js/4.js                41.50 KiB           3.92 KiB
        dist/static/js/5.js                35.68 KiB           3.38 KiB
        dist/static/js/10.js               25.06 KiB           3.46 KiB
        dist/static/js/12.js               7.84 KiB            1.12 KiB
        dist/static/js/14.js               5.85 KiB            1.13 KiB
        dist/static/js/13.js               2.96 KiB            0.75 KiB
        dist/static/js/15.js               0.54 KiB            0.27 KiB
      
        Images and other types of assets omitted.
      
       DONE  Build complete. The dist directory is ready to be deployed.
       INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deployment.html
            
      npm notice 
      npm notice New major version of npm available! 8.19.2 -> 9.1.2
      npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.1.2>
      npm notice Run `npm install -g npm@9.1.2` to update!
      npm notice 

    Completed in 25.961s

===> EXPORTING
Adding layer 'paketo-buildpacks/ca-certificates:helper'
Adding layer 'launch.sbom'
Adding 1/1 app layer(s)
Adding layer 'launcher'
Adding layer 'config'
Adding label 'io.buildpacks.lifecycle.metadata'
Adding label 'io.buildpacks.build.metadata'
Adding label 'io.buildpacks.project.metadata'
**ERROR: failed to export: determining entrypoint: tried to set web to default but it doesn't exist**
```

**Comment by AidanDelaney** [comment] 2022-11-23 08:25
Hi @Sunny-001.  I don't think your build error is to do with volume mounting.  It looks like it's failing to find an entrypoint.  Using the paketo buildpacks (see https://paketo.io/community/ for their support channels) you may need an `npm start` script or `Procfile` to specify the entrypoint?

**Comment by AidanDelaney** [comment] 2022-12-27 08:47
Closing as we don't think the issue is with our docs.  Please re-open if this is incorrect.

**Closed by AidanDelaney** 2022-12-27 08:47 UTC
